/**
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.modelspeak.agentLang;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.modelspeak.agentLang.AgentLangPackage
 * @generated
 */
public interface AgentLangFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AgentLangFactory eINSTANCE = uk.ac.kcl.inf.modelspeak.agentLang.impl.AgentLangFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Game</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game</em>'.
   * @generated
   */
  Game createGame();

  /**
   * Returns a new object of class '<em>Move</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Move</em>'.
   * @generated
   */
  Move createMove();

  /**
   * Returns a new object of class '<em>Research Question</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Research Question</em>'.
   * @generated
   */
  ResearchQuestion createResearchQuestion();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Requirement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Requirement</em>'.
   * @generated
   */
  Requirement createRequirement();

  /**
   * Returns a new object of class '<em>Experiment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Experiment</em>'.
   * @generated
   */
  Experiment createExperiment();

  /**
   * Returns a new object of class '<em>Theory</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Theory</em>'.
   * @generated
   */
  Theory createTheory();

  /**
   * Returns a new object of class '<em>General Theory</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>General Theory</em>'.
   * @generated
   */
  GeneralTheory createGeneralTheory();

  /**
   * Returns a new object of class '<em>Literature Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Literature Reference</em>'.
   * @generated
   */
  LiteratureReference createLiteratureReference();

  /**
   * Returns a new object of class '<em>Propose RQ</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Propose RQ</em>'.
   * @generated
   */
  ProposeRQ createProposeRQ();

  /**
   * Returns a new object of class '<em>Propose Requirement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Propose Requirement</em>'.
   * @generated
   */
  ProposeRequirement createProposeRequirement();

  /**
   * Returns a new object of class '<em>Attack Requirement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attack Requirement</em>'.
   * @generated
   */
  AttackRequirement createAttackRequirement();

  /**
   * Returns a new object of class '<em>Redefine Requirement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Redefine Requirement</em>'.
   * @generated
   */
  RedefineRequirement createRedefineRequirement();

  /**
   * Returns a new object of class '<em>Retract Requirement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Retract Requirement</em>'.
   * @generated
   */
  RetractRequirement createRetractRequirement();

  /**
   * Returns a new object of class '<em>Support Requirement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Support Requirement</em>'.
   * @generated
   */
  SupportRequirement createSupportRequirement();

  /**
   * Returns a new object of class '<em>Propose Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Propose Model</em>'.
   * @generated
   */
  ProposeModel createProposeModel();

  /**
   * Returns a new object of class '<em>Support Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Support Model</em>'.
   * @generated
   */
  SupportModel createSupportModel();

  /**
   * Returns a new object of class '<em>Replace Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Replace Model</em>'.
   * @generated
   */
  ReplaceModel createReplaceModel();

  /**
   * Returns a new object of class '<em>Counter Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Counter Model</em>'.
   * @generated
   */
  CounterModel createCounterModel();

  /**
   * Returns a new object of class '<em>Attack Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attack Model</em>'.
   * @generated
   */
  AttackModel createAttackModel();

  /**
   * Returns a new object of class '<em>Revise Requirement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Revise Requirement</em>'.
   * @generated
   */
  ReviseRequirement createReviseRequirement();

  /**
   * Returns a new object of class '<em>Propose Experiment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Propose Experiment</em>'.
   * @generated
   */
  ProposeExperiment createProposeExperiment();

  /**
   * Returns a new object of class '<em>Support Experiment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Support Experiment</em>'.
   * @generated
   */
  SupportExperiment createSupportExperiment();

  /**
   * Returns a new object of class '<em>Attack Experiment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attack Experiment</em>'.
   * @generated
   */
  AttackExperiment createAttackExperiment();

  /**
   * Returns a new object of class '<em>Retract Experiment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Retract Experiment</em>'.
   * @generated
   */
  RetractExperiment createRetractExperiment();

  /**
   * Returns a new object of class '<em>Study Done</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Study Done</em>'.
   * @generated
   */
  StudyDone createStudyDone();

  /**
   * Returns a new object of class '<em>Not Convinced</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Not Convinced</em>'.
   * @generated
   */
  NotConvinced createNotConvinced();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AgentLangPackage getAgentLangPackage();

} //AgentLangFactory
