/**
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.modelspeak.agentLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Propose Requirement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.modelspeak.agentLang.ProposeRequirement#getRequirement <em>Requirement</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.modelspeak.agentLang.AgentLangPackage#getProposeRequirement()
 * @model
 * @generated
 */
public interface ProposeRequirement extends Move
{
  /**
   * Returns the value of the '<em><b>Requirement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requirement</em>' containment reference.
   * @see #setRequirement(Requirement)
   * @see uk.ac.kcl.inf.modelspeak.agentLang.AgentLangPackage#getProposeRequirement_Requirement()
   * @model containment="true"
   * @generated
   */
  Requirement getRequirement();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.modelspeak.agentLang.ProposeRequirement#getRequirement <em>Requirement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Requirement</em>' containment reference.
   * @see #getRequirement()
   * @generated
   */
  void setRequirement(Requirement value);

} // ProposeRequirement
