/**
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.modelspeak.agentLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Replace Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.modelspeak.agentLang.ReplaceModel#getModel <em>Model</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.modelspeak.agentLang.ReplaceModel#getNewModel <em>New Model</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.modelspeak.agentLang.AgentLangPackage#getReplaceModel()
 * @model
 * @generated
 */
public interface ReplaceModel extends Move
{
  /**
   * Returns the value of the '<em><b>Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' reference.
   * @see #setModel(Model)
   * @see uk.ac.kcl.inf.modelspeak.agentLang.AgentLangPackage#getReplaceModel_Model()
   * @model
   * @generated
   */
  Model getModel();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.modelspeak.agentLang.ReplaceModel#getModel <em>Model</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' reference.
   * @see #getModel()
   * @generated
   */
  void setModel(Model value);

  /**
   * Returns the value of the '<em><b>New Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Model</em>' containment reference.
   * @see #setNewModel(Model)
   * @see uk.ac.kcl.inf.modelspeak.agentLang.AgentLangPackage#getReplaceModel_NewModel()
   * @model containment="true"
   * @generated
   */
  Model getNewModel();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.modelspeak.agentLang.ReplaceModel#getNewModel <em>New Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New Model</em>' containment reference.
   * @see #getNewModel()
   * @generated
   */
  void setNewModel(Model value);

} // ReplaceModel
