/**
 * generated by Xtext 2.36.0
 */
package uk.ac.kcl.inf.modelspeak.agentLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Retract Experiment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.modelspeak.agentLang.RetractExperiment#getExperiment <em>Experiment</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.modelspeak.agentLang.AgentLangPackage#getRetractExperiment()
 * @model
 * @generated
 */
public interface RetractExperiment extends Move
{
  /**
   * Returns the value of the '<em><b>Experiment</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Experiment</em>' reference.
   * @see #setExperiment(Experiment)
   * @see uk.ac.kcl.inf.modelspeak.agentLang.AgentLangPackage#getRetractExperiment_Experiment()
   * @model
   * @generated
   */
  Experiment getExperiment();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.modelspeak.agentLang.RetractExperiment#getExperiment <em>Experiment</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Experiment</em>' reference.
   * @see #getExperiment()
   * @generated
   */
  void setExperiment(Experiment value);

} // RetractExperiment
