/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.modellingDialogue.theoryStore;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.modellingDialogue.theoryStore.Model#getRequirements <em>Requirements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.modellingDialogue.theoryStore.TheoryStorePackage#getModel()
 * @model
 * @generated
 */
public interface Model extends Element
{
  /**
   * Returns the value of the '<em><b>Requirements</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.modellingDialogue.theoryStore.Requirement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requirements</em>' reference list.
   * @see org.xtext.example.modellingDialogue.theoryStore.TheoryStorePackage#getModel_Requirements()
   * @model
   * @generated
   */
  EList<Requirement> getRequirements();

} // Model
