/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.modellingDialogue.theoryStore;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Requirement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.modellingDialogue.theoryStore.TheoryStorePackage#getRequirement()
 * @model
 * @generated
 */
public interface Requirement extends Element
{
} // Requirement
