/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.modellingDialogue.theoryStore;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Theory</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.modellingDialogue.theoryStore.Theory#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.modellingDialogue.theoryStore.TheoryStorePackage#getTheory()
 * @model
 * @generated
 */
public interface Theory extends Element
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.modellingDialogue.theoryStore.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' reference list.
   * @see org.xtext.example.modellingDialogue.theoryStore.TheoryStorePackage#getTheory_Elements()
   * @model
   * @generated
   */
  EList<Element> getElements();

} // Theory
