/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.modelspeak.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.modelspeak.theorystore.ui.internal.TheorystoreActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TheoryStoreLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TheorystoreActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TheorystoreActivator activator = TheorystoreActivator.getInstance();
		return activator != null ? activator.getInjector(TheorystoreActivator.UK_AC_KCL_INF_MODELSPEAK_THEORYSTORELANG) : null;
	}

}
