/**
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.modelspeak.agentLang.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.inf.modelspeak.agentLang.AgentLangPackage;
import uk.ac.kcl.inf.modelspeak.agentLang.Experiment;
import uk.ac.kcl.inf.modelspeak.agentLang.Model;
import uk.ac.kcl.inf.modelspeak.agentLang.Requirement;
import uk.ac.kcl.inf.modelspeak.agentLang.ReviseRequirement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Revise Requirement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.modelspeak.agentLang.impl.ReviseRequirementImpl#getModel <em>Model</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.modelspeak.agentLang.impl.ReviseRequirementImpl#getRequirement <em>Requirement</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.modelspeak.agentLang.impl.ReviseRequirementImpl#getNewRequirement <em>New Requirement</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.modelspeak.agentLang.impl.ReviseRequirementImpl#getExperiment <em>Experiment</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReviseRequirementImpl extends MoveImpl implements ReviseRequirement
{
  /**
   * The cached value of the '{@link #getModel() <em>Model</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModel()
   * @generated
   * @ordered
   */
  protected Model model;

  /**
   * The cached value of the '{@link #getRequirement() <em>Requirement</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequirement()
   * @generated
   * @ordered
   */
  protected Requirement requirement;

  /**
   * The cached value of the '{@link #getNewRequirement() <em>New Requirement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNewRequirement()
   * @generated
   * @ordered
   */
  protected Requirement newRequirement;

  /**
   * The cached value of the '{@link #getExperiment() <em>Experiment</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExperiment()
   * @generated
   * @ordered
   */
  protected Experiment experiment;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReviseRequirementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AgentLangPackage.Literals.REVISE_REQUIREMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model getModel()
  {
    if (model != null && model.eIsProxy())
    {
      InternalEObject oldModel = (InternalEObject)model;
      model = (Model)eResolveProxy(oldModel);
      if (model != oldModel)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AgentLangPackage.REVISE_REQUIREMENT__MODEL, oldModel, model));
      }
    }
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model basicGetModel()
  {
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setModel(Model newModel)
  {
    Model oldModel = model;
    model = newModel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AgentLangPackage.REVISE_REQUIREMENT__MODEL, oldModel, model));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Requirement getRequirement()
  {
    if (requirement != null && requirement.eIsProxy())
    {
      InternalEObject oldRequirement = (InternalEObject)requirement;
      requirement = (Requirement)eResolveProxy(oldRequirement);
      if (requirement != oldRequirement)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AgentLangPackage.REVISE_REQUIREMENT__REQUIREMENT, oldRequirement, requirement));
      }
    }
    return requirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Requirement basicGetRequirement()
  {
    return requirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRequirement(Requirement newRequirement)
  {
    Requirement oldRequirement = requirement;
    requirement = newRequirement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AgentLangPackage.REVISE_REQUIREMENT__REQUIREMENT, oldRequirement, requirement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Requirement getNewRequirement()
  {
    return newRequirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNewRequirement(Requirement newNewRequirement, NotificationChain msgs)
  {
    Requirement oldNewRequirement = newRequirement;
    newRequirement = newNewRequirement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AgentLangPackage.REVISE_REQUIREMENT__NEW_REQUIREMENT, oldNewRequirement, newNewRequirement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNewRequirement(Requirement newNewRequirement)
  {
    if (newNewRequirement != newRequirement)
    {
      NotificationChain msgs = null;
      if (newRequirement != null)
        msgs = ((InternalEObject)newRequirement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AgentLangPackage.REVISE_REQUIREMENT__NEW_REQUIREMENT, null, msgs);
      if (newNewRequirement != null)
        msgs = ((InternalEObject)newNewRequirement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AgentLangPackage.REVISE_REQUIREMENT__NEW_REQUIREMENT, null, msgs);
      msgs = basicSetNewRequirement(newNewRequirement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AgentLangPackage.REVISE_REQUIREMENT__NEW_REQUIREMENT, newNewRequirement, newNewRequirement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Experiment getExperiment()
  {
    if (experiment != null && experiment.eIsProxy())
    {
      InternalEObject oldExperiment = (InternalEObject)experiment;
      experiment = (Experiment)eResolveProxy(oldExperiment);
      if (experiment != oldExperiment)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AgentLangPackage.REVISE_REQUIREMENT__EXPERIMENT, oldExperiment, experiment));
      }
    }
    return experiment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Experiment basicGetExperiment()
  {
    return experiment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExperiment(Experiment newExperiment)
  {
    Experiment oldExperiment = experiment;
    experiment = newExperiment;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AgentLangPackage.REVISE_REQUIREMENT__EXPERIMENT, oldExperiment, experiment));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AgentLangPackage.REVISE_REQUIREMENT__NEW_REQUIREMENT:
        return basicSetNewRequirement(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AgentLangPackage.REVISE_REQUIREMENT__MODEL:
        if (resolve) return getModel();
        return basicGetModel();
      case AgentLangPackage.REVISE_REQUIREMENT__REQUIREMENT:
        if (resolve) return getRequirement();
        return basicGetRequirement();
      case AgentLangPackage.REVISE_REQUIREMENT__NEW_REQUIREMENT:
        return getNewRequirement();
      case AgentLangPackage.REVISE_REQUIREMENT__EXPERIMENT:
        if (resolve) return getExperiment();
        return basicGetExperiment();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AgentLangPackage.REVISE_REQUIREMENT__MODEL:
        setModel((Model)newValue);
        return;
      case AgentLangPackage.REVISE_REQUIREMENT__REQUIREMENT:
        setRequirement((Requirement)newValue);
        return;
      case AgentLangPackage.REVISE_REQUIREMENT__NEW_REQUIREMENT:
        setNewRequirement((Requirement)newValue);
        return;
      case AgentLangPackage.REVISE_REQUIREMENT__EXPERIMENT:
        setExperiment((Experiment)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AgentLangPackage.REVISE_REQUIREMENT__MODEL:
        setModel((Model)null);
        return;
      case AgentLangPackage.REVISE_REQUIREMENT__REQUIREMENT:
        setRequirement((Requirement)null);
        return;
      case AgentLangPackage.REVISE_REQUIREMENT__NEW_REQUIREMENT:
        setNewRequirement((Requirement)null);
        return;
      case AgentLangPackage.REVISE_REQUIREMENT__EXPERIMENT:
        setExperiment((Experiment)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AgentLangPackage.REVISE_REQUIREMENT__MODEL:
        return model != null;
      case AgentLangPackage.REVISE_REQUIREMENT__REQUIREMENT:
        return requirement != null;
      case AgentLangPackage.REVISE_REQUIREMENT__NEW_REQUIREMENT:
        return newRequirement != null;
      case AgentLangPackage.REVISE_REQUIREMENT__EXPERIMENT:
        return experiment != null;
    }
    return super.eIsSet(featureID);
  }

} //ReviseRequirementImpl
