/**
 * generated by Xtext 2.36.0
 */
package uk.ac.kcl.inf.modelspeak.agentLang.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.inf.modelspeak.agentLang.AgentLangPackage;
import uk.ac.kcl.inf.modelspeak.agentLang.StudyDone;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Study Done</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StudyDoneImpl extends MoveImpl implements StudyDone
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StudyDoneImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AgentLangPackage.Literals.STUDY_DONE;
  }

} //StudyDoneImpl
