/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.modelspeak


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TheoryStoreLangRuntimeModule extends AbstractTheoryStoreLangRuntimeModule {
}
