/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.modelspeak.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTheoryStoreLangScopeProvider extends DelegatingScopeProvider {
}
