/*
 * generated by Xtext 2.36.0
 */
package uk.ac.kcl.inf.modelspeak.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.modelspeak.parser.antlr.internal.InternalAgentLangParser;
import uk.ac.kcl.inf.modelspeak.services.AgentLangGrammarAccess;

public class AgentLangParser extends AbstractAntlrParser {

	@Inject
	private AgentLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAgentLangParser createParser(XtextTokenStream stream) {
		return new InternalAgentLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Game";
	}

	public AgentLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AgentLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
