/*
 * generated by Xtext 2.36.0
 */
package uk.ac.kcl.inf.modelspeak.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.modelspeak.agents.ui.internal.AgentsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AgentLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(AgentsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		AgentsActivator activator = AgentsActivator.getInstance();
		return activator != null ? activator.getInjector(AgentsActivator.UK_AC_KCL_INF_MODELSPEAK_AGENTLANG) : null;
	}

}
