/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mod.modellingSpeak;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Not Convinced</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mod.modellingSpeak.NotConvinced#getModel <em>Model</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getNotConvinced()
 * @model
 * @generated
 */
public interface NotConvinced extends Move
{
  /**
   * Returns the value of the '<em><b>Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' reference.
   * @see #setModel(Model)
   * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getNotConvinced_Model()
   * @model
   * @generated
   */
  Model getModel();

  /**
   * Sets the value of the '{@link org.xtext.example.mod.modellingSpeak.NotConvinced#getModel <em>Model</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' reference.
   * @see #getModel()
   * @generated
   */
  void setModel(Model value);

} // NotConvinced
