/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mod.modellingSpeak;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Propose Experiment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mod.modellingSpeak.ProposeExperiment#getModel <em>Model</em>}</li>
 *   <li>{@link org.xtext.example.mod.modellingSpeak.ProposeExperiment#getExperiment <em>Experiment</em>}</li>
 *   <li>{@link org.xtext.example.mod.modellingSpeak.ProposeExperiment#getRequirement <em>Requirement</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getProposeExperiment()
 * @model
 * @generated
 */
public interface ProposeExperiment extends Move
{
  /**
   * Returns the value of the '<em><b>Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' reference.
   * @see #setModel(Model)
   * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getProposeExperiment_Model()
   * @model
   * @generated
   */
  Model getModel();

  /**
   * Sets the value of the '{@link org.xtext.example.mod.modellingSpeak.ProposeExperiment#getModel <em>Model</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' reference.
   * @see #getModel()
   * @generated
   */
  void setModel(Model value);

  /**
   * Returns the value of the '<em><b>Experiment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Experiment</em>' containment reference.
   * @see #setExperiment(Experiment)
   * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getProposeExperiment_Experiment()
   * @model containment="true"
   * @generated
   */
  Experiment getExperiment();

  /**
   * Sets the value of the '{@link org.xtext.example.mod.modellingSpeak.ProposeExperiment#getExperiment <em>Experiment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Experiment</em>' containment reference.
   * @see #getExperiment()
   * @generated
   */
  void setExperiment(Experiment value);

  /**
   * Returns the value of the '<em><b>Requirement</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requirement</em>' reference.
   * @see #setRequirement(Requirement)
   * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getProposeExperiment_Requirement()
   * @model
   * @generated
   */
  Requirement getRequirement();

  /**
   * Sets the value of the '{@link org.xtext.example.mod.modellingSpeak.ProposeExperiment#getRequirement <em>Requirement</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Requirement</em>' reference.
   * @see #getRequirement()
   * @generated
   */
  void setRequirement(Requirement value);

} // ProposeExperiment
