/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mod.modellingSpeak;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Retract Experiment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mod.modellingSpeak.RetractExperiment#getExperiment <em>Experiment</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getRetractExperiment()
 * @model
 * @generated
 */
public interface RetractExperiment extends Move
{
  /**
   * Returns the value of the '<em><b>Experiment</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Experiment</em>' reference.
   * @see #setExperiment(Experiment)
   * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getRetractExperiment_Experiment()
   * @model
   * @generated
   */
  Experiment getExperiment();

  /**
   * Sets the value of the '{@link org.xtext.example.mod.modellingSpeak.RetractExperiment#getExperiment <em>Experiment</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Experiment</em>' reference.
   * @see #getExperiment()
   * @generated
   */
  void setExperiment(Experiment value);

} // RetractExperiment
