/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mod.modellingSpeak;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Revise Requirement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mod.modellingSpeak.ReviseRequirement#getModel <em>Model</em>}</li>
 *   <li>{@link org.xtext.example.mod.modellingSpeak.ReviseRequirement#getRequirement <em>Requirement</em>}</li>
 *   <li>{@link org.xtext.example.mod.modellingSpeak.ReviseRequirement#getNewRequirement <em>New Requirement</em>}</li>
 *   <li>{@link org.xtext.example.mod.modellingSpeak.ReviseRequirement#getExperiment <em>Experiment</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getReviseRequirement()
 * @model
 * @generated
 */
public interface ReviseRequirement extends Move
{
  /**
   * Returns the value of the '<em><b>Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' reference.
   * @see #setModel(Model)
   * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getReviseRequirement_Model()
   * @model
   * @generated
   */
  Model getModel();

  /**
   * Sets the value of the '{@link org.xtext.example.mod.modellingSpeak.ReviseRequirement#getModel <em>Model</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' reference.
   * @see #getModel()
   * @generated
   */
  void setModel(Model value);

  /**
   * Returns the value of the '<em><b>Requirement</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requirement</em>' reference.
   * @see #setRequirement(Requirement)
   * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getReviseRequirement_Requirement()
   * @model
   * @generated
   */
  Requirement getRequirement();

  /**
   * Sets the value of the '{@link org.xtext.example.mod.modellingSpeak.ReviseRequirement#getRequirement <em>Requirement</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Requirement</em>' reference.
   * @see #getRequirement()
   * @generated
   */
  void setRequirement(Requirement value);

  /**
   * Returns the value of the '<em><b>New Requirement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Requirement</em>' containment reference.
   * @see #setNewRequirement(Requirement)
   * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getReviseRequirement_NewRequirement()
   * @model containment="true"
   * @generated
   */
  Requirement getNewRequirement();

  /**
   * Sets the value of the '{@link org.xtext.example.mod.modellingSpeak.ReviseRequirement#getNewRequirement <em>New Requirement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New Requirement</em>' containment reference.
   * @see #getNewRequirement()
   * @generated
   */
  void setNewRequirement(Requirement value);

  /**
   * Returns the value of the '<em><b>Experiment</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Experiment</em>' reference.
   * @see #setExperiment(Experiment)
   * @see org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage#getReviseRequirement_Experiment()
   * @model
   * @generated
   */
  Experiment getExperiment();

  /**
   * Sets the value of the '{@link org.xtext.example.mod.modellingSpeak.ReviseRequirement#getExperiment <em>Experiment</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Experiment</em>' reference.
   * @see #getExperiment()
   * @generated
   */
  void setExperiment(Experiment value);

} // ReviseRequirement
