/**
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.inf.modelspeak.theoryStoreLang.Requirement;
import uk.ac.kcl.inf.modelspeak.theoryStoreLang.TheoryStoreLangPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Requirement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RequirementImpl extends ElementImpl implements Requirement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RequirementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TheoryStoreLangPackage.Literals.REQUIREMENT;
  }

} //RequirementImpl
