/**
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.modelspeak.theoryStoreLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Theory Store</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.TheoryStore#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.TheoryStoreLangPackage#getTheoryStore()
 * @model
 * @generated
 */
public interface TheoryStore extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.TheoryStoreLangPackage#getTheoryStore_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

} // TheoryStore
