/**
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.modelspeak.theoryStoreLang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.TheoryStoreLangFactory
 * @model kind="package"
 * @generated
 */
public interface TheoryStoreLangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "theoryStoreLang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/modelspeak/TheoryStoreLang";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "theoryStoreLang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TheoryStoreLangPackage eINSTANCE = uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreImpl <em>Theory Store</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreImpl
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getTheoryStore()
   * @generated
   */
  int THEORY_STORE = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEORY_STORE__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Theory Store</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEORY_STORE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ElementImpl
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__CONTENT = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ModelImpl
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getModel()
   * @generated
   */
  int MODEL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONTENT = ELEMENT__CONTENT;

  /**
   * The feature id for the '<em><b>Requirements</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__REQUIREMENTS = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryImpl <em>Theory</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryImpl
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getTheory()
   * @generated
   */
  int THEORY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEORY__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEORY__CONTENT = ELEMENT__CONTENT;

  /**
   * The feature id for the '<em><b>Elements</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEORY__ELEMENTS = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Theory</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THEORY_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.RequirementImpl <em>Requirement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.RequirementImpl
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getRequirement()
   * @generated
   */
  int REQUIREMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT__CONTENT = ELEMENT__CONTENT;

  /**
   * The number of structural features of the '<em>Requirement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIREMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ExperimentImpl <em>Experiment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ExperimentImpl
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getExperiment()
   * @generated
   */
  int EXPERIMENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIMENT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIMENT__CONTENT = ELEMENT__CONTENT;

  /**
   * The feature id for the '<em><b>Model</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIMENT__MODEL = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Requirements</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIMENT__REQUIREMENTS = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Experiment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.TheoryStore <em>Theory Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Theory Store</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.TheoryStore
   * @generated
   */
  EClass getTheoryStore();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.TheoryStore#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.TheoryStore#getElements()
   * @see #getTheoryStore()
   * @generated
   */
  EReference getTheoryStore_Elements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Element#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Content</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.Element#getContent()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Content();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the reference list '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Model#getRequirements <em>Requirements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Requirements</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.Model#getRequirements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Requirements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Theory <em>Theory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Theory</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.Theory
   * @generated
   */
  EClass getTheory();

  /**
   * Returns the meta object for the reference list '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Theory#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Elements</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.Theory#getElements()
   * @see #getTheory()
   * @generated
   */
  EReference getTheory_Elements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Requirement <em>Requirement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Requirement</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.Requirement
   * @generated
   */
  EClass getRequirement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Experiment <em>Experiment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Experiment</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.Experiment
   * @generated
   */
  EClass getExperiment();

  /**
   * Returns the meta object for the reference list '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Experiment#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Model</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.Experiment#getModel()
   * @see #getExperiment()
   * @generated
   */
  EReference getExperiment_Model();

  /**
   * Returns the meta object for the reference list '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.Experiment#getRequirements <em>Requirements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Requirements</em>'.
   * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.Experiment#getRequirements()
   * @see #getExperiment()
   * @generated
   */
  EReference getExperiment_Requirements();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TheoryStoreLangFactory getTheoryStoreLangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreImpl <em>Theory Store</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreImpl
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getTheoryStore()
     * @generated
     */
    EClass THEORY_STORE = eINSTANCE.getTheoryStore();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference THEORY_STORE__ELEMENTS = eINSTANCE.getTheoryStore_Elements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ElementImpl
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__CONTENT = eINSTANCE.getElement_Content();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ModelImpl
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Requirements</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__REQUIREMENTS = eINSTANCE.getModel_Requirements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryImpl <em>Theory</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryImpl
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getTheory()
     * @generated
     */
    EClass THEORY = eINSTANCE.getTheory();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference THEORY__ELEMENTS = eINSTANCE.getTheory_Elements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.RequirementImpl <em>Requirement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.RequirementImpl
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getRequirement()
     * @generated
     */
    EClass REQUIREMENT = eINSTANCE.getRequirement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ExperimentImpl <em>Experiment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.ExperimentImpl
     * @see uk.ac.kcl.inf.modelspeak.theoryStoreLang.impl.TheoryStoreLangPackageImpl#getExperiment()
     * @generated
     */
    EClass EXPERIMENT = eINSTANCE.getExperiment();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPERIMENT__MODEL = eINSTANCE.getExperiment_Model();

    /**
     * The meta object literal for the '<em><b>Requirements</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPERIMENT__REQUIREMENTS = eINSTANCE.getExperiment_Requirements();

  }

} //TheoryStoreLangPackage
