/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mod.modellingSpeak.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mod.modellingSpeak.AttackModel;
import org.xtext.example.mod.modellingSpeak.Model;
import org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage;
import org.xtext.example.mod.modellingSpeak.Theory;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attack Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mod.modellingSpeak.impl.AttackModelImpl#getModel <em>Model</em>}</li>
 *   <li>{@link org.xtext.example.mod.modellingSpeak.impl.AttackModelImpl#getTheory <em>Theory</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttackModelImpl extends MoveImpl implements AttackModel
{
  /**
   * The cached value of the '{@link #getModel() <em>Model</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModel()
   * @generated
   * @ordered
   */
  protected Model model;

  /**
   * The cached value of the '{@link #getTheory() <em>Theory</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTheory()
   * @generated
   * @ordered
   */
  protected Theory theory;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttackModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModellingSpeakPackage.Literals.ATTACK_MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model getModel()
  {
    if (model != null && model.eIsProxy())
    {
      InternalEObject oldModel = (InternalEObject)model;
      model = (Model)eResolveProxy(oldModel);
      if (model != oldModel)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ModellingSpeakPackage.ATTACK_MODEL__MODEL, oldModel, model));
      }
    }
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model basicGetModel()
  {
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setModel(Model newModel)
  {
    Model oldModel = model;
    model = newModel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModellingSpeakPackage.ATTACK_MODEL__MODEL, oldModel, model));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Theory getTheory()
  {
    return theory;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTheory(Theory newTheory, NotificationChain msgs)
  {
    Theory oldTheory = theory;
    theory = newTheory;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModellingSpeakPackage.ATTACK_MODEL__THEORY, oldTheory, newTheory);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTheory(Theory newTheory)
  {
    if (newTheory != theory)
    {
      NotificationChain msgs = null;
      if (theory != null)
        msgs = ((InternalEObject)theory).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModellingSpeakPackage.ATTACK_MODEL__THEORY, null, msgs);
      if (newTheory != null)
        msgs = ((InternalEObject)newTheory).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModellingSpeakPackage.ATTACK_MODEL__THEORY, null, msgs);
      msgs = basicSetTheory(newTheory, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModellingSpeakPackage.ATTACK_MODEL__THEORY, newTheory, newTheory));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ModellingSpeakPackage.ATTACK_MODEL__THEORY:
        return basicSetTheory(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ModellingSpeakPackage.ATTACK_MODEL__MODEL:
        if (resolve) return getModel();
        return basicGetModel();
      case ModellingSpeakPackage.ATTACK_MODEL__THEORY:
        return getTheory();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ModellingSpeakPackage.ATTACK_MODEL__MODEL:
        setModel((Model)newValue);
        return;
      case ModellingSpeakPackage.ATTACK_MODEL__THEORY:
        setTheory((Theory)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ModellingSpeakPackage.ATTACK_MODEL__MODEL:
        setModel((Model)null);
        return;
      case ModellingSpeakPackage.ATTACK_MODEL__THEORY:
        setTheory((Theory)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ModellingSpeakPackage.ATTACK_MODEL__MODEL:
        return model != null;
      case ModellingSpeakPackage.ATTACK_MODEL__THEORY:
        return theory != null;
    }
    return super.eIsSet(featureID);
  }

} //AttackModelImpl
