/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mod.modellingSpeak.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.mod.modellingSpeak.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ModellingSpeakFactoryImpl extends EFactoryImpl implements ModellingSpeakFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ModellingSpeakFactory init()
  {
    try
    {
      ModellingSpeakFactory theModellingSpeakFactory = (ModellingSpeakFactory)EPackage.Registry.INSTANCE.getEFactory(ModellingSpeakPackage.eNS_URI);
      if (theModellingSpeakFactory != null)
      {
        return theModellingSpeakFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ModellingSpeakFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModellingSpeakFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ModellingSpeakPackage.GAME: return createGame();
      case ModellingSpeakPackage.MOVE: return createMove();
      case ModellingSpeakPackage.MODEL: return createModel();
      case ModellingSpeakPackage.REQUIREMENT: return createRequirement();
      case ModellingSpeakPackage.EXPERIMENT: return createExperiment();
      case ModellingSpeakPackage.THEORY: return createTheory();
      case ModellingSpeakPackage.PROPOSE_REQUIREMENT: return createProposeRequirement();
      case ModellingSpeakPackage.ATTACK_REQUIREMENT: return createAttackRequirement();
      case ModellingSpeakPackage.REDEFINE_REQUIREMENT: return createRedefineRequirement();
      case ModellingSpeakPackage.RETRACT_REQUIREMENT: return createRetractRequirement();
      case ModellingSpeakPackage.SUPPORT_REQUIREMENT: return createSupportRequirement();
      case ModellingSpeakPackage.PROPOSE_MODEL: return createProposeModel();
      case ModellingSpeakPackage.SUPPORT_MODEL: return createSupportModel();
      case ModellingSpeakPackage.REPLACE_MODEL: return createReplaceModel();
      case ModellingSpeakPackage.COUNTER_MODEL: return createCounterModel();
      case ModellingSpeakPackage.ATTACK_MODEL: return createAttackModel();
      case ModellingSpeakPackage.REVISE_REQUIREMENT: return createReviseRequirement();
      case ModellingSpeakPackage.PROPOSE_EXPERIMENT: return createProposeExperiment();
      case ModellingSpeakPackage.SUPPORT_EXPERIMENT: return createSupportExperiment();
      case ModellingSpeakPackage.ATTACK_EXPERIMENT: return createAttackExperiment();
      case ModellingSpeakPackage.RETRACT_EXPERIMENT: return createRetractExperiment();
      case ModellingSpeakPackage.STUDY_DONE: return createStudyDone();
      case ModellingSpeakPackage.NOT_CONVINCED: return createNotConvinced();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Game createGame()
  {
    GameImpl game = new GameImpl();
    return game;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Move createMove()
  {
    MoveImpl move = new MoveImpl();
    return move;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Requirement createRequirement()
  {
    RequirementImpl requirement = new RequirementImpl();
    return requirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Experiment createExperiment()
  {
    ExperimentImpl experiment = new ExperimentImpl();
    return experiment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Theory createTheory()
  {
    TheoryImpl theory = new TheoryImpl();
    return theory;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProposeRequirement createProposeRequirement()
  {
    ProposeRequirementImpl proposeRequirement = new ProposeRequirementImpl();
    return proposeRequirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AttackRequirement createAttackRequirement()
  {
    AttackRequirementImpl attackRequirement = new AttackRequirementImpl();
    return attackRequirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RedefineRequirement createRedefineRequirement()
  {
    RedefineRequirementImpl redefineRequirement = new RedefineRequirementImpl();
    return redefineRequirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RetractRequirement createRetractRequirement()
  {
    RetractRequirementImpl retractRequirement = new RetractRequirementImpl();
    return retractRequirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SupportRequirement createSupportRequirement()
  {
    SupportRequirementImpl supportRequirement = new SupportRequirementImpl();
    return supportRequirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProposeModel createProposeModel()
  {
    ProposeModelImpl proposeModel = new ProposeModelImpl();
    return proposeModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SupportModel createSupportModel()
  {
    SupportModelImpl supportModel = new SupportModelImpl();
    return supportModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReplaceModel createReplaceModel()
  {
    ReplaceModelImpl replaceModel = new ReplaceModelImpl();
    return replaceModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CounterModel createCounterModel()
  {
    CounterModelImpl counterModel = new CounterModelImpl();
    return counterModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AttackModel createAttackModel()
  {
    AttackModelImpl attackModel = new AttackModelImpl();
    return attackModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReviseRequirement createReviseRequirement()
  {
    ReviseRequirementImpl reviseRequirement = new ReviseRequirementImpl();
    return reviseRequirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProposeExperiment createProposeExperiment()
  {
    ProposeExperimentImpl proposeExperiment = new ProposeExperimentImpl();
    return proposeExperiment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SupportExperiment createSupportExperiment()
  {
    SupportExperimentImpl supportExperiment = new SupportExperimentImpl();
    return supportExperiment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AttackExperiment createAttackExperiment()
  {
    AttackExperimentImpl attackExperiment = new AttackExperimentImpl();
    return attackExperiment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RetractExperiment createRetractExperiment()
  {
    RetractExperimentImpl retractExperiment = new RetractExperimentImpl();
    return retractExperiment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StudyDone createStudyDone()
  {
    StudyDoneImpl studyDone = new StudyDoneImpl();
    return studyDone;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotConvinced createNotConvinced()
  {
    NotConvincedImpl notConvinced = new NotConvincedImpl();
    return notConvinced;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ModellingSpeakPackage getModellingSpeakPackage()
  {
    return (ModellingSpeakPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ModellingSpeakPackage getPackage()
  {
    return ModellingSpeakPackage.eINSTANCE;
  }

} //ModellingSpeakFactoryImpl
