/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mod.modellingSpeak.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mod.modellingSpeak.ModellingSpeakPackage;
import org.xtext.example.mod.modellingSpeak.StudyDone;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Study Done</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StudyDoneImpl extends MoveImpl implements StudyDone
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StudyDoneImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModellingSpeakPackage.Literals.STUDY_DONE;
  }

} //StudyDoneImpl
