/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.modellingDialogue.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTheoryStoreScopeProvider extends DelegatingScopeProvider {
}
