/*
 * generated by Xtext 2.35.0
 */
package uk.ac.kcl.inf.modelspeak.ide


/**
 * Use this class to register ide components.
 */
class TheoryStoreLangIdeModule extends AbstractTheoryStoreLangIdeModule {
}
