/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mod


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ModellingSpeakStandaloneSetup extends ModellingSpeakStandaloneSetupGenerated {

	def static void doSetup() {
		new ModellingSpeakStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
