/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.mod.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ModellingSpeakUiModule extends AbstractModellingSpeakUiModule {
}
