/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.modellingDialogue.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.theoryStore.ui.internal.TheoryStoreActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TheoryStoreExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TheoryStoreActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TheoryStoreActivator activator = TheoryStoreActivator.getInstance();
		return activator != null ? activator.getInjector(TheoryStoreActivator.ORG_XTEXT_EXAMPLE_MODELLINGDIALOGUE_THEORYSTORE) : null;
	}

}
