/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.modellingDialogue.theoryStore.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.modellingDialogue.theoryStore.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class TheoryStoreFactoryImpl extends EFactoryImpl implements TheoryStoreFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static TheoryStoreFactory init()
  {
    try
    {
      TheoryStoreFactory theTheoryStoreFactory = (TheoryStoreFactory)EPackage.Registry.INSTANCE.getEFactory(TheoryStorePackage.eNS_URI);
      if (theTheoryStoreFactory != null)
      {
        return theTheoryStoreFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new TheoryStoreFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TheoryStoreFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case TheoryStorePackage.THEORY_STORE: return createTheoryStore();
      case TheoryStorePackage.ELEMENT: return createElement();
      case TheoryStorePackage.MODEL: return createModel();
      case TheoryStorePackage.THEORY: return createTheory();
      case TheoryStorePackage.REQUIREMENT: return createRequirement();
      case TheoryStorePackage.EXPERIMENT: return createExperiment();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TheoryStore createTheoryStore()
  {
    TheoryStoreImpl theoryStore = new TheoryStoreImpl();
    return theoryStore;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Element createElement()
  {
    ElementImpl element = new ElementImpl();
    return element;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Theory createTheory()
  {
    TheoryImpl theory = new TheoryImpl();
    return theory;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Requirement createRequirement()
  {
    RequirementImpl requirement = new RequirementImpl();
    return requirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Experiment createExperiment()
  {
    ExperimentImpl experiment = new ExperimentImpl();
    return experiment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TheoryStorePackage getTheoryStorePackage()
  {
    return (TheoryStorePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static TheoryStorePackage getPackage()
  {
    return TheoryStorePackage.eINSTANCE;
  }

} //TheoryStoreFactoryImpl
