/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.modellingDialogue.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TheoryStoreAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/modellingDialogue/parser/antlr/internal/InternalTheoryStore.tokens");
	}
}
